version: '3.1'

services:
  postgres:
    image: postgres:16-0alpine3.18
    container_name: postgres_db
    environment:
      POSTGRES_DB: transcendance
      POSTGRES_USER: dieri
      POSTGRES_PASSWORD: dieri
    ports:
      - "5432:5432"
    volumes:
      - ./database:/var/lib/postgresql/data