version: "3.1"

services:
  postgres:
    image: postgres:16.0
    container_name: postgres_db
    environment:
      POSTGRES_DB: transcendance
      POSTGRES_USER: dieri
      POSTGRES_PASSWORD: dieri
    ports:
      - "5432:5432"
    volumes:
      - my-db:/var/lib/postgresql/data
    restart: always

volumes:
  my-db: